name: Build Project for PR

on: # Run only when a pull request is created or updated to the main branch
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Clone code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Install JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Step 3: Build Maven project
      - name: Build with Maven
        run: mvn clean install

